language: haskell

ghc:
  - 7.8

install:
  - cabal update
  - cabal configure --enable-tests

script: cabal build -j && cabal test -j --show-details=always

before_install:
  - git submodule update --init --recursive
